FROM node:12.18.0

WORKDIR /

RUN apt-get update && apt-get install -y vim less
RUN echo 'alias ll="ls -al --color"' >> ~/.bashrc
RUN echo 'set clipboard=unnamedplus' >> ~/.vimrc

RUN mkdir client
WORKDIR /client

COPY ./package.json .
COPY ./yarn.lock .
RUN rm -rf node_modules
RUN yarn install --production --network-timeout 100000

EXPOSE 3000
EXPOSE 35729

CMD [ "npm", "start" ]
