version: "3.7"

services:
  stay_a_while_server:
    image: registry.digitalocean.com/stayawhile/stay_a_while_server:1.0
    container_name: stay_a_while_server
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - stay_a_while
    environment:
      APP_NAME: stay_a_while
      SERVER_PORT: ${SERVER_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      REACT_EDITOR: ${REACT_EDITOR}
      HOST: ${HOST}
      IS_DEVELOPMENT: ${IS_DEVELOPMENT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - ${SERVER_PORT}
      - ${REDIS_PORT}
  redis:
    image: "redis:6.0.5"
    container_name: "stay_a_while_redis"
    volumes:
      - stay_a_while_redis:/data
    networks:
      - stay_a_while
    entrypoint: redis-server --appendonly yes # Persistence mode
    ports:
      # Use corla_redis:6379 to connect from another docker container
      # Use 127.0.0.1:${REDIS_HOST_PORT} to connect from host
      - "${REDIS_DOCKER_HOST_PORT}:${REDIS_PORT}"
    command: ["--notify-keyspace-events", "Khs"]

volumes:
  stay_a_while_redis:
    name: stay_a_while_redis
networks:
  stay_a_while:
    name: stay_a_while
    driver: bridge
